ForloopAI/forloop_common_structures

forloop_common_structures/core/database.py
forloop_common_structures/core/trigger.py

Dependencies:
- [https://github.com/ForloopAI/forloop_platform/pull/781](https://github.com/ForloopAI/forloop_platform/pull/781)
- [https://github.com/ForloopAI/forloop_modules/pull/17](https://github.com/ForloopAI/forloop_modules/pull/17)
Introduces:
- Updated/cleaned up Trigger dataclass/APIschema/DBmodel

Triggers update & Job scheduler

---

forloop_common_structures/core/database.py
forloop_common_structures/core/result.py
forloop_common_structures/core/trigger.py

Depending on this:
- [https://github.com/ForloopAI/forloop_platform/pull/788](https://github.com/ForloopAI/forloop_platform/pull/788)
Dependencies:
- [https://github.com/ForloopAI/forloop_common_structures/pull/4](https://github.com/ForloopAI/forloop_common_structures/pull/4)
Introduces:
- Added size/type to `Result`

Progress stream changes

---

forloop_common_structures/core/initial_variable.py
forloop_common_structures/core/job.py
setup.py

Dependency to:
- [https://github.com/ForloopAI/forloop_platform/pull/845](https://github.com/ForloopAI/forloop_platform/pull/845)

jakub_prototype_job to dev

---

forloop_common_structures/core/initial_variable.py
forloop_common_structures/core/job.py
forloop_common_structures/core/variable.py

Dependency to:
- [https://github.com/ForloopAI/forloop_platform/pull/849](https://github.com/ForloopAI/forloop_platform/pull/849)

Jakub_init_var to dev

---

forloop_common_structures/core/database.py

Required for: [https://github.com/ForloopAI/forloop_platform/pull/852](https://github.com/ForloopAI/forloop_platform/pull/852)

Change Database.project_uid to str --> main

---

forloop_common_structures/core/node.py

Linked PRs:
* [https://github.com/ForloopAI/forloop_platform/pull/862](https://github.com/ForloopAI/forloop_platform/pull/862)
* [https://github.com/ForloopAI/forloop_modules/pull/51](https://github.com/ForloopAI/forloop_modules/pull/51)

daniel/fix-shown-df-field-refresh --> dev

---

forloop_common_structures/core/database.py

Dependency to:
- https://github.com/ForloopAI/forloop_platform/pull/887

Introduce `Database` persistence

---

forloop_common_structures/core/session.py

Dependency to:
- https://github.com/ForloopAI/forloop_platform/pull/896

Correct Session objects

---

forloop_common_structures/core/initial_variable.py
forloop_common_structures/core/job.py
forloop_common_structures/core/variable.py

Dependency to:
- https://github.com/ForloopAI/forloop_platform/pull/912

clean up `Variable` to rely on `pipeline_job_uid` and not `pipeline_uid`

---

forloop_common_structures/core/job.py
forloop_common_structures/core/trigger.py
forloop_common_structures/core/user.py

Dependency to:
- https://github.com/ForloopAI/forloop_platform/pull/938

Jakub bugfixes 6

---

forloop_common_structures/core/browser_elements.py

Dependency to:
- https://github.com/ForloopAI/forloop_platform/pull/940

NEW: Introduce persistence of WebExtractor elements and screenshots

---

forloop_common_structures/core/browser_elements.py

Dependency to:
- https://github.com/ForloopAI/forloop_platform/pull/942

NEW: Add `url` attribute to `Screenshot`

---

forloop_common_structures/core/plan.py
forloop_common_structures/core/project.py
forloop_common_structures/core/user.py

Dependency to:
- https://github.com/ForloopAI/forloop_platform/pull/949

Stripe integration

---

forloop_common_structures/core/job.py
forloop_common_structures/core/trigger.py

Dependency to:
- https://github.com/ForloopAI/forloop_platform/pull/951

Jakub vars

---

forloop_common_structures/core/job.py

Dependency to:
- https://github.com/ForloopAI/forloop_platform/pull/953

Jakub fixes

---

forloop_common_structures/core/pipeline.py

Dependency to:
* https://github.com/ForloopAI/forloop_platform/pull/954

Add 'system_reactivation_status' arg to Pipeline

---

forloop_common_structures/core/plan.py

Dependency to:
- https://github.com/ForloopAI/forloop_platform/pull/958

Add `is_active` column to `SubscriptionPlans`

---

forloop_common_structures/core/browser_elements.py

Dependency to:
- https://github.com/ForloopAI/forloop_platform/pull/964

Extend `Elements` dataclass with a `SimilarElements` json type

---

forloop_common_structures/core/initial_variable.py
forloop_common_structures/core/variable.py

Dependency to:
https://github.com/ForloopAI/forloop_platform/pull/990
Changes:
* adds `tuple` type option to `size` argument of `Variable` and `InitialVariable`

Change 'size' arg type to Union[int, tuple, None] --> main

---

forloop_common_structures/database_models.py

Fixes Xlsx DB crashes for nodes with non-empty params.

Fix escape string mechanism - faulty --> main
